Mellomlagring
bekk/spire-nav-brevgenerator pull request #13
Opened 2022-09-27 12:42 UTC by sberbom

Ønsker å kunne mellomlagre data. Har derfor lagret metoder for å representere staten i komponenten som et json objekt, og tolke et json objekt for å oppdatere staten på komponenten. 

For brevmalen "du får overgangsstønad" ligger det nå inne mellomlagring mockdata.

Brev-api -> laget mock metoder for å hente og publisere data til backend.
Brevtgenerator -> Ny global state for data som skal mellomlagres. mellomlagringDelseksjonerState
Context -> Ny global state for data som skal mellomlagres.
Reducer -> Ny global state for data som skal mellomlagres.
Delseksjon -> Populerer delseksjonen med mellomlagret data. Oppdaterer mellomlagringstaten ved endringer i delseksjonen.
Dropdown -> Støtte for å vise mellomlagret data
Flettefelt -> Støtte for å vise mellomlagret data
Flettefelter -> Støtte for å vise mellomlagret data
Skjema -> initier mellomlagringsstate for gjeldene brevmal. Mellomlagringskapp er kommentert ut siden vi ikke har noen kobling mot backen enda.
Skjema.css -> Style 😎 
Mellomlagring.ts -> mellomlagringstyper
typer.ts -> oppdatert med mellomlagringsstate
flettefeltutils -> laget hjelpemetoder for å finne fletteflet. Brukes nå både i redring og mellomlagring
utils/mellomlagring -> Hjelpemetoder for mellomlagring
sanityutils -> Fikser bug i rendering av flettefelt
utils/utils -> generelle hjelpemetoder

2022-09-27 12:57 UTC, kolbjornkelly approved these changes
Kode (10/10) + beskrivende PR (10/10) = helt rått (20/10)

2022-09-27 14:58 UTC, sarahjelle requested changes
Et par ting som ikke fungerer helt som det skal, se kommentarer i kode for mer informasjon

Sykt bra at du har byttet mange navn så de blir mye mer forståelig😍

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +    const [flettefelt, settFlettefelt] = useState<flettefelt[][]>([]);
<3 <3 <3

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/skjema.tsx
> +import { Button, Select } from '@navikt/ds-react';
Denne brukes ikke, burde ikke egt lintingen stoppe dette?

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/skjema.tsx
> +                } else if (mellomlagretBrev !== undefined) {
Kan dette være en else?

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +    const innholdTilFritekstTabell = (
Enten burde denne metoden også flyttes til utils, eller så bør `innholdTilFlettefeltTabell()` flyttes hit. Begge brukes kun her

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
>              settFritekstTabell(nyFritekstTabell);
Friteksttabell må oppdateres med mellomlagret avsnitt for å fungere riktig. Fritekstabell settes nå til å være tom, og ved endringer vil følgende skje: 

- Hvis man velger i dropdown før man trykker i fritekstfeltet vil dette oppdatere et felt i friteksttabellen. Så vil hele friteksttabellen gjøres om til streng for å vises. Siden resterende elementer i tabellen er tomme vil resten av innholdet i friteksten slettes. 
- Hvis man trykker i fritekstfeltet med en gang og så gjør endring i dropdown fjernes alt som var der og man får kun det som akkurat ble valgt

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +        const mellomlagringDelseksjonKopi = dypKopi(
Lite forklarende navn på denne funksjonen

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +            ).fill('');
Gjøres dette for å fylle flettetabellen med tomme strenger? F.eks. om den finner tre flettefelt så får man `["", "", ""]`?

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +            mellomlagringDelseksjonKopi.innhold[innholdIndeks][flettefeltIndeks] = e.target.value;
Skjønner ikke helt hvordan dette fungerer. Er det en dobbel tabell her?

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/flettefelt.tsx
> +            defaultValue={mellomlagretVerdi}
Håndterer denne at mellomlagretVerdi ikke eksisterer?

2022-09-27 14:58 UTC, sarahjelle commented on src/komponenter/flettefelt.tsx
> +            defaultValue={mellomlagretVerdi}
Og: må ikke input-felter ha en value som oppdateres? (vet det ikke er fra denne PR-en men kom på det nå)

2022-09-28 06:57 UTC, sberbom commented on src/komponenter/skjema.tsx
> +import { Button, Select } from '@navikt/ds-react';
Jo er noe feil med lintingen. Tror aldri det har vært helt riktig i dette repoet. Grunnen til at jeg ikke har fjernet den er at jeg har kommentert ut knappen lengere nede i filen. Knappen skal være med når backenden er klar, men enn så lenge er det slags feature toggle at knappen er kommentert ut.

2022-09-28 08:18 UTC, sarahjelle commented on src/brev-api.ts
> +    return sanityBaseURL + "/?query=" + query;
Hvorfor er dette endret?

2022-09-28 08:19 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +            const mellomlagretDelseskjon = mellomlagringDelseksjonerState[delseksjonIndeks];
![bitmoji](https://sdk.bitmoji.com/render/panel/1101d250-5ec5-477a-83f0-235d4a61fc49-34b31aac-d7b8-4791-b90a-32559917e97e-v1.png?transparent=1&palette=1&width=246)![bitmoji](https://sdk.bitmoji.com/render/panel/1101d250-5ec5-477a-83f0-235d4a61fc49-34b31aac-d7b8-4791-b90a-32559917e97e-v1.png?transparent=1&palette=1&width=246)

2022-09-28 08:19 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +
![bitmoji](https://sdk.bitmoji.com/render/panel/1101d250-5ec5-477a-83f0-235d4a61fc49-34b31aac-d7b8-4791-b90a-32559917e97e-v1.png?transparent=1&palette=1&width=246)

2022-09-28 08:22 UTC, sarahjelle commented on src/komponenter/delseksjon.tsx
> +        setmellomlagringDelseksjonState(mellomlagringDelseksjonKopi);
Hvorfor måtte du legge til dette?

2022-09-28 08:31 UTC, sarahjelle approved these changes
Nå ser det veldig bra ut! Problemene fra tidligere er fikset
![image](https://user-images.githubusercontent.com/46678893/192729970-2c751cb0-997b-4ee5-9f56-8b4230318adf.png)

2022-09-28 08:32 UTC, merged