Opprydding i globale states
bekk/spire-nav-brevgenerator pull request #23
Opened 2022-10-04 13:40 UTC by sarahjelle

## Problem 🤯
Vi har tidligere hatt mange ulike globale states som vedlikeholdes kontinuerlig, og friteksten har blitt lagret som både tabell og som strenger (i avnsittState).

## Løsning ✨
I hovedsak: Fjerne `avsnittState` og bytte den ut med `delseksjonerState`. Dette er en state med følgende format: 

```
export type delseksjonType = {
    innhold: (string[] | dropdown)[];
    fritekstTabell: string[][];
};
```
Denne endringen fører til: 

- Alt knyttet til `<Fritekst />` lagres kun på `fritekstTabell`-format, aldri som strenger. Omgjøringen til strenger skjer i de ulike komponentene som tidligere brukte `avsnittState` eller `fritekst` (state i delseksjon)
- Når det skjer endringer i delseksjon er den lokale staten `fritekst` fjernet: nå brukes kun `fritekst`. 
-  Det er ikke lenger en egen context for mellomlagring. Mellomlagringsobjektet settes sammen av andre states før kallet kjøres. 

## Kjent bug 🐛
Det er ikke mulig å legge til en ny paragraf helt i slutten av et fritekstfelt. Siden Sigmund jobber med logikken knyttet til dette atm har jeg ikke rørt dette i denne PR-en.

2022-10-05 06:49 UTC, kolbjornkelly approved these changes
Helt fantastisk!

2022-10-05 06:49 UTC, kolbjornkelly commented on src/komponenter/skjema.tsx
> +    // TODO: Fjerne avsnitt her
🤔

2022-10-05 06:49 UTC, kolbjornkelly commented on src/typer/typer.ts
> +export type delseksjonType = {
"delseksjonType" bryter med konvensjonen vi har brukt til å navngi de andre custom-typene. Er det mulig å kalle denne "delseksjon", og heller bruke "sanityDelseksjon" der man har brukt "delseksjon" til nå?

2022-10-05 07:17 UTC, sarahjelle commented on src/typer/typer.ts
> +export type delseksjonType = {
Skal se på det!

2022-10-05 07:17 UTC, sarahjelle commented on src/komponenter/skjema.tsx
> +    // TODO: Fjerne avsnitt her
Tror ikke den kan fjernes enda pga backend (litt usikker)

2022-10-05 08:51 UTC, sberbom approved these changes
Nice 👍

2022-10-05 08:51 UTC, sberbom commented on src/utils/skjemaUtils.ts
> +    let antallDelSeksjoner = 0;
Brukes denne til noe?

2022-10-05 08:51 UTC, sberbom commented on src/komponenter/skjema.tsx
> +            avsnitt: [],
Fjerne denne?

2022-10-07 08:00 UTC, sarahjelle commented on src/utils/skjemaUtils.ts
> +    let antallDelSeksjoner = 0;
Nopp, fjernet nå!

2022-10-07 08:20 UTC, kolbjornkelly requested changes
Nice! Se kommentar

2022-10-07 08:20 UTC, kolbjornkelly commented on src/brev-api.ts
> +const backendURL = 'http://localhost:8080';
Denne må vel endres tilbake?

2022-10-07 08:24 UTC, sarahjelle commented on src/brev-api.ts
> +const backendURL = 'http://localhost:8080';
Oh no du rakk å se på den før jeg rakk å pushe på nytt uten🥲, men skal være good nå

2022-10-07 08:28 UTC, kolbjornkelly approved these changes
Gåsehud over hele kroppen. Dette var rett og slett rørende bra, Sara.

2022-10-07 08:30 UTC, merged