Mellomlagre alert
bekk/spire-nav-brevgenerator pull request #25
Opened 2022-10-05 13:24 UTC by tengssimen

Øsnker: Alert som viser om mellomlagring er vellykket eller ikke ved buttonclick. 

Løst: Returnerer en Nav sin Alert komponent i skjema når man klikker på mellomlagringsknappen. Ved klikk blir en ny state kalt `alertSkalVises` satt til true i 2.5 sekunder. `PostMellomlagring()` i brev-api returnerer nå en `Promise<boolean>` som blir brukt til å sette en state `vellykketMellomlagring` i skjema som bestemmer om Alerten som vises skal være av typen success eller error.

2022-10-05 13:27 UTC, tengssimen commented
Oops - endringene på hentBrevmal i brev-api er bare prettier

2022-10-05 13:30 UTC, kolbjornkelly requested changes
Bra jobba! 

(husk å oppdatere versjon)

2022-10-05 13:57 UTC, sberbom approved these changes
Rått. 200poeng

2022-10-06 05:41 UTC, kolbjornkelly approved these changes

2022-10-06 06:31 UTC, merged