Nullstill fritekst
bekk/spire-nav-brevgenerator pull request #29
Opened 2022-10-07 13:15 UTC by sarahjelle

# Problem 🤯
Hvis saksbehandler redigerer den initielle teksten fra sanity gjennom fritekstfeltet har de ingen mulighet til å tilbakestille dette til originalteksten. 

# Løsning ✨
Legge til en _tilbakestill_ knapp under hvert fritekst-felt. Ved trykk på denne knappen endres teksten i friteksten tilbake til det som er definert av brevmalen fra sanity (+ verdiene i flettefelt).

2022-10-07 13:21 UTC, sarahjelle commented on src/utils/delseksjonUtils.ts
> +    ).fill({ ...tomtFlettefelt });
Lager en kopi av tomtFlettefelt så man ikke endrer på tomtFlettefelt-objektet når man gjør oppdateringer i flettefelt-inputs.

2022-10-10 06:21 UTC, kolbjornkelly requested changes
Herlig! Litta leif i import, men koden kjører mjukere enn smør når det er fikset 🧈

2022-10-10 06:21 UTC, kolbjornkelly commented on src/komponenter/delseksjon.tsx
> +import { erInnholdSanitySanityDropdown, erInnholdTekstObjekt } from '../utils/sanityUtils';
Did you mean `erInnholdSanityDropdown`?

2022-10-10 06:21 UTC, kolbjornkelly commented on src/komponenter/delseksjon.tsx
> +    innholdTilFritekstTabell,
Dobbel import

2022-10-10 10:26 UTC, kolbjornkelly approved these changes

2022-10-10 10:46 UTC, sberbom commented on src/utils/flettefeltUtils.ts
> +    let flettefeltIndeks = 0;
Husk å inkrementere denne 👍

2022-10-10 10:46 UTC, sberbom commented on src/utils/delseksjonUtils.ts
> +    delseksjonIndeks: number
Her kan du sende inn rett delseksjonState med en gang i stedet for å sende inn både delseksjonstate og delsesjonIndeks. Den "lookupen" kan du gjøre der metoden kalles.

2022-10-10 12:33 UTC, tengssimen approved these changes
Funker bra nå etter siste endringen!

2022-10-10 13:14 UTC, merged